import {
    ImageWOT1Desktop,
    ImageWOT1Mobile,
    ImageWOT2Desktop,
    ImageWOT2Mobile,
    ImageWOT3Desktop,
    ImageWOT3Mobile,
    ImageWOT4Mobile,
    ImageWOT5Desktop,
    ImageWOT5Mobile,
    ImageWOT6Desktop,
    ImageWOT6Mobile,
    ImageWOT7Desktop,
    ImageWOT7Mobile,
    ImageWOT8Desktop,
    ImageWOT8Mobile,
    ImageWOT9Desktop,
    ImageWOT9Mobile,
} from "@/public/images/images";
import { Tutorial } from "./interface";

export const tutorials: Tutorial[] = [
    {
        imageMobile: ImageWOT1Mobile,
        imageDesktop: ImageWOT1Desktop,
        title: "Getting Started: How to Create Your Account on Our Platform",
        steps: 13,
        duration: "05:00 mins",
    },
    {
        imageMobile: ImageWOT2Mobile,
        imageDesktop: ImageWOT2Desktop,
        title: "Uploading Your Products: A Step-by-Step Guide",
        steps: 13,
        duration: "05:00 mins",
    },
    {
        imageMobile: ImageWOT3Mobile,
        imageDesktop: ImageWOT3Desktop,
        title: "How to Add Funds to Your Wallet: A Step-by-Step Guide",
        steps: 13,
        duration: "05:00 mins",
    },
    {
        imageMobile: ImageWOT4Mobile,
        imageDesktop: ImageWOT5Desktop,
        title: "Account Settings: How to Update Your Profile and Information",
        steps: 13,
        duration: "05:00 mins",
    },
    {
        imageMobile: ImageWOT5Mobile,
        imageDesktop: ImageWOT5Desktop,
        title: "Creating Coupons: A Step-by-Step Guide",
        steps: 13,
        duration: "05:00 mins",
    },
    {
        imageMobile: ImageWOT6Mobile,
        imageDesktop: ImageWOT6Desktop,
        title: "Security Settings: How to Keep Your Account Safe and Secure",
        steps: 13,
        duration: "05:00 mins",
    },
    {
        imageMobile: ImageWOT7Mobile,
        imageDesktop: ImageWOT7Desktop,
        title: "Withdrawing Funds from Your Wallet: A How-To Guide",
        steps: 13,
        duration: "05:00 mins",
    },
    {
        imageMobile: ImageWOT8Mobile,
        imageDesktop: ImageWOT8Desktop,
        title: "Leveraging Marketing Tools: Promote Your Products Effectively",
        steps: 13,
        duration: "05:00 mins",
    },
    {
        imageMobile: ImageWOT9Mobile,
        imageDesktop: ImageWOT9Desktop,
        title: "Processing Orders: From Start to Finish",
        steps: 13,
        duration: "05:00 mins",
    },
];
