import { ImageProduct1 } from "@/public/images/landingPage/images";

export const tabs = [
    { label: "All", value: "all" },
    { label: "New", value: "new" },
    { label: "Pending", value: "pending" },
    { label: "Shipped", value: "shipped" },
    { label: "Delivered", value: "delivered" },
    { label: "Cancelled", value: "cancelled" },
    { label: "Returned", value: "returned" },
];

export const orderTabs = ["ALL", "NEW", "PENDING", "SHIPPED", "DELIVERED", "CANCELLED_ORDER", "RETURNED"];

// export const orderTabs = [
//     "ALL",
//     "ACCEPTED",
//     "AWAITING_PICK_UP",
//     "CANCELLED_ORDER",
//     "CANCELLED_PAYMENT",
//     "CARD_PAYMENT_FAILED",
//     "CONFIRMED",
//     "DECLINED",
//     "DELIVERED",
//     "DROPPED_AT_CHECKOUT",
//     "FAILED_PAYMENT_CONFIRMATION",
//     "FULFILLED",
//     "NEW",
//     "NEW_WITH_ISSUE",
//     "PENDING",
//     "PENDING_PAYMENT",
//     "PROCESSING",
//     "RETURNED",
//     "SHIPPED",
//     "USSD_PAYMENT_FAILED",
// ];

export const ordersList = [
    {
        productImage: ImageProduct1,
        orderId: "KG-6445496452",
        productName: "Bose Silver Color Quietcomfort 45 Headset Bluetooth Wireless Noise",
        dateOfPurchase: "01 Aug 2024",
        amount: "2,400",
        paymentStatus: "paid",
        orderStatus: "new",
        quantity: 4,
        orderDate: "12 August 2024",
        deliveryDate: "14 August 2024",
    },
    {
        productImage: ImageProduct1,
        orderId: "KG-6445496452",
        productName: "Bose Gold Color Quietcomfort 45 Headset Bluetooth Wireless Noise",
        dateOfPurchase: "01 Aug 2024",
        amount: "2,300",
        paymentStatus: "paid",
        orderStatus: "cancelled",
        quantity: 1,
        orderDate: "12 August 2024",
        deliveryDate: "14 August 2024",
    },
    {
        productImage: ImageProduct1,
        orderId: "KG-6445496452",
        productName: "Bose Diamond Color Quietcomfort 45 Headset Bluetooth Wireless Noise",
        dateOfPurchase: "01 Aug 2024",
        amount: "2,200",
        paymentStatus: "paid",
        orderStatus: "processing",
        quantity: 14,
        orderDate: "12 August 2024",
        deliveryDate: "14 August 2024",
    },
    {
        productImage: ImageProduct1,
        orderId: "KG-6445496452",
        productName: "Bose Red Color Quietcomfort 45 Headset Bluetooth Wireless Noise",
        dateOfPurchase: "01 Aug 2024",
        amount: "2,100",
        paymentStatus: "paid",
        orderStatus: "shipped",
        quantity: 8,
        orderDate: "12 August 2024",
        deliveryDate: "14 August 2024",
    },
    {
        productImage: ImageProduct1,
        orderId: "KG-6445496452",
        productName: "Bose Green Color Quietcomfort 45 Headset Bluetooth Wireless Noise",
        dateOfPurchase: "01 Aug 2024",
        amount: "2,000",
        paymentStatus: "paid",
        orderStatus: "delivered",
        quantity: 9,
        orderDate: "12 August 2024",
        deliveryDate: "14 August 2024",
    },
];
